# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Complex Systems Winter School
email: complexsystemsturkey@gmail.com
description: >
  Dynamics on network structures are fundamental models for the behaviour of complex systems, modelling physical, biological and societal systems, including the brain, food webs, epidemic disease in populations, power grids and many other. Such dynamical networks can exhibit behavior in which deterministic chaos, exhibiting unpredictability and disorder, coexists with synchronisation, a classical paradigm of order. During the past decades, our mathematical understanding of collective behavior on complex networks has increased significantly. In this winter school, we will survey the main theory behind synchronization phenomena in networks and discuss applications to secure communications, parameter estimation and the anticipation of chaos.
keywords: >
  dynamical systems, chaos, complex systems, school, 
baseurl: ""
github_username: "complex-systems-turkey"
schedule: https://osem.hillhacks.in/conferences/hillhacks2017/schedule

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
collections:
  sessions:
    output: false
  dates:
    output: false